name: CI Pipeline
# Hi
on:
  push:
    branches:
      - testing   # Trigger on pushes to 'testing' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Login to Azure Container Registry
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Step 4: Build and push Product Service
      - name: Build and Push Product Service
        run: |
          IMAGE_NAME=product_service
          IMAGE_TAG=latest
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG ./backend/product_service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG

      # Step 5: Build and push Order Service
      - name: Build and Push Order Service
        run: |
          IMAGE_NAME=order_service
          IMAGE_TAG=latest
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG ./backend/order_service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG

      # Step 6: Build and push Customer Service
      - name: Build and Push Customer Service
        run: |
          IMAGE_NAME=customer_service
          IMAGE_TAG=latest
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG ./backend/customer_service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG

      # Step 7: Build and push Frontend
      - name: Build and Push Frontend
        run: |
          IMAGE_NAME=frontend
          IMAGE_TAG=latest
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG ./frontend
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG
